language: elixir
elixir:
- 1.3
otp_release:
- 18.2
sudo: false
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database peepchat_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: hCYrMUefKDs2+bOzFO0hANXBpmAvBJQ7lM1ZToozptAKSV5JFB9AJdV6DRqyM9y9FGVNHDmw15HMOFg7EZJsYCJvVspKavVR+HhrQwwXXZ4jnxKdhO7nKsX0aMMpaWVoVKDVLuvAM64z49mH1t/VoHzcRFluN2L2qzw8ANHR3gVwXoUS+B4/wODAcRLlxvM5QFly/F6jlLT3m7nuLyVfH+iNriO61eejo082xELcwVNmeN8sOpH+sRvi5rAPSoV0vv1117nN6xPYwa8mn77SLvmPjfo0ZYX3ScqfQdE/plbOdSmwd37op2ZIgh2ckCtNXwnTmr7/t5piyIJ+J8jmbfEvHlWi/KNtbHcD6l+sU+2l6+Jk/6kGlSHSg/Jzm1LfQguvAAcCdksThbBBchJle85IeBjrUSMRIDVDNfCETq/+FVKHscqqLT+ZtN+TFFeJJtq2j4ILBM8mYj2gxZSZRXGFIwjWXmW8GzSD/ydf0A0Uob5O0+mplUmqt2lROQ7x8gjs32YlmTxmhrhmAeTqLqpRgk32w6F/arZPm/XA01DCAHw9HcsqEjP7tgqFUWp1eJYdVQdKMZmNzJKHflaezIB3rlfnB65xsjOJ2EyTGPsRIp5seVOBylSshIE6FoB6zceY1+l7qAw3Kj5ZePTPxIIeTliiy2NgwdTUXzUpw7E=
  app: peaceful-ridge-40485
  on:
    repo: koriroys/sport_backend
